### ISSUE TITLE
Twitter @user mentions and emojis/emoticons missing

### ISSUE THREAD

**Issue by badjoerichards** [godkingjay/selenium-twitter-scraper#1]
Nice work! But it seems like user twitter handle mentions i.e. @elon @jay are not recorded in the .csv outputs.

Also emojis / emoticons are removed as well.

Are we able to have them in the "content" or in 2 new columns like "mentions" and "emojis"?

**Comment by godkingjay** [comment]
Hello @badjoerichards , thank you for raising this issue.

It is actually possible to save the mentions and emojis in the .csv output. However we need to convert the emoji into another form like unicode or byte sequence since it's not possible to save the emoji as it is.

[feat: scrape mentions and emojis](https://github.com/godkingjay/selenium-twitter-scraper/commit/407a7174383a3c8930fd84e1ee48de64ff35f99e)

**Comment by badjoerichards** [comment]
Perfect!
