### ISSUE TITLE
(request) Scrape each poster's [FOLLOWERS] and [FOLLOWING] count?

### ISSUE THREAD

**Issue by badjoerichards** [godkingjay/selenium-twitter-scraper#4]
Is it possible to get the user's [FOLLOWERS] and [FOLLOWING] count as 2 new columns of data in the .csv?

Very useful information when scraping.

Thanks

**Comment by godkingjay** [comment]
It's possible to get the [FOLLOWING] and [FOLLOWERS] count of the tweet's poster, however this will definitely slow down the scraping process because in twitter, the user's followers and following is not directly included in the tweet. So I will only add them as an optional data to be scraped. I'll make a commit later, I'm currently doing some tests and optimizing the scraper. There will be significant improvements to the scraper especially when scraping without including the [FOLLOWERS] and [FOLLOWING] count.

**Comment by godkingjay** [comment]
To scrape followers and following count:

```bash
python scraper --add="pd"
```

[feat: optionally scrape followers and following](https://github.com/godkingjay/selenium-twitter-scraper/commit/069b0cc24a89e8a70c1e5524ee85a156a5cadf5d)

[docs: Sample code for additional data to scrape.](https://github.com/godkingjay/selenium-twitter-scraper/commit/5c98c3ebc4ac956ac809ab04074d1ead2911cfa4)

**Comment by badjoerichards** [comment]
This is great! Thank you
